---
exclude: ['README.markdown']
permalink: ':title'
highlighter: rouge
url: "https://dfabreguette-ap.github.io/"  # the base hostname & protocol for your site, e.g. http://example.com
safe: false
title: 'Ammy API'
sass:
  sass_dir: ./assets
