---
exclude: ['README.markdown']
permalink: ':title'
highlighter: rouge
baseurl: "/ammy_api/" # the subpath of your site, e.g. /blog. If there is no subpath for your site, use an empty string ""
url: "https://dfabreguette-ap.github.io/"  # the base hostname & protocol for your site, e.g. http://example.com
safe: false
title: 'Ammy API'
sass:
  sass_dir: ./assets
